# Generated by Django 4.1.7 on 2023-05-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(choices=[('', 'Selecione um assunto'), ('duvidas', 'Dúvidas'), ('elogios', 'Elogios'), ('sugestões', 'Sugestões'), ('reclamações', 'Reclamações'), ('outros', 'Outros')], default='', max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mensagem', models.TextField(max_length=100)),
            ],
        ),
    ]
