# Generated by Django 4.1.7 on 2023-05-02 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_imagem_capa_post_resumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 5, 2, 23, 43, 38, 330010, tzinfo=datetime.timezone.utc)),
        ),
    ]
