# Generated by Django 4.1.7 on 2023-05-24 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 5, 24, 1, 56, 32, 155764, tzinfo=datetime.timezone.utc)),
        ),
    ]
