# Generated by Django 4.1.7 on 2023-05-26 23:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_data_publicacao_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 5, 26, 23, 22, 4, 864705, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='PostSituacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('post_situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_situacao', to='blog.post')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.situacao')),
            ],
            options={
                'unique_together': {('post', 'situacao')},
            },
        ),
        migrations.RemoveField(
            model_name='situacao',
            name='posts',
        ),
        migrations.AddField(
            model_name='situacao',
            name='posts',
            field=models.ManyToManyField(related_name='PostSituacao', through='blog.PostSituacao', to='blog.post'),
        ),
    ]
