# Generated by Django 4.1.7 on 2023-05-27 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
        ('blog', '0017_alter_post_data_publicacao_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.perfil'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateField(),
        ),
    ]
